DELIMITER $$

CREATE PROCEDURE  BUSCAR_POR_CPF (IN CPF INT)
	BEGIN
		SELECT * FROM CLIENTE WHERE CPF=@CPF;
	END $$
	DELIMITER;
		

CREATE PROCEDURE  BUSCAR_POR_NOME (IN NOME VARCHAR)
	BEGIN
		SELECT * FROM CLIENTE WHERE NOME LIKE '%' + @NOME + '%';
	END $$
	DELIMITER;

CREATE PROCEDURE  EXCLUIR_POR_NOME (IN NOME VARCHAR)
	BEGIN
		DELETE FROM CLIENTE WHERE LIKE '%' + @NOME + '%';
	END $$
	DELIMITER;	

CREATE PROCEDURE  EXCLUIR_POR_CPF (IN CPF INT)
	BEGIN
		DELETE FROM CLIENTE WHERE CPF=@CPF;
	END $$
	DELIMITER;

		
